### ISSUE TITLE
Question regarding the theory part

### ISSUE THREAD

**Issue by reemastha706** [xmhk/liblp#1]
Hi. Sorry, this is not really a bug but could you explain why E[ind2] was multiplied by J0/K0?? According to the theory, E=J1/J0 and K1/K0. When I use this formula directly, the mode seems to have wrong distribution. However, when I use your method, it works. 

Thanks.

**Comment by xmhk** [comment]
Hi,
I'm sorry but I've written that code some time ago, so I can't fully remember. When solving the mode equations for a step-index fiber, one finds that the solutions in the Core and in the Cladding have to be Bessel functions Jm and Km respectively. To get physical solutions, the mode has to be continuous at the transition points (core radius).

Thus, one has to scale the Bessel functions accordingly, which i did by introducing the factor `fak = jv(m,u)/kn(m, w)`.
However this is some shortcut, the proper way would be to determine the scaling constants from the differential equation. Some lines below in the code, the maximum mode intensity is scaled to unity anyway, so I did not bother to calculate the scaling factors properly.

Best, Christoph

PS: it may also be that the `scipy` definitions of the Bessel functions may be slightly different in terms of y-scaling compared to my math book, but I can't remember for sure.
